# Generated by Django 4.2.20 on 2026-03-27 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationOtp',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('otp_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=5)),
                ('send_count', models.IntegerField(default=1)),
                ('last_sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('used', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'registration_otps',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.TextField()),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_staff', models.BooleanField(db_index=True, default=False)),
                ('date_joined', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('profile', models.JSONField(blank=True, default=dict)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('company_url', models.URLField(blank=True, default='')),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['username'], name='users_usernam_baeb4b_idx'), models.Index(fields=['email'], name='users_email_4b85f2_idx'), models.Index(fields=['created_at'], name='users_created_6541e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'password_resets',
                'indexes': [models.Index(fields=['email', 'used'], name='password_re_email_40850e_idx'), models.Index(fields=['expires_at'], name='password_re_expires_d36310_idx')],
            },
        ),
    ]
