# Generated by Django 4.2.20 on 2026-05-03 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_useraccount_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationOtp',
        ),
    ]
