"""
DevOps service for work item and integration-related business logic.
This service delegates to the integrations app for external platform operations.
"""

from typing import Dict, List, Optional, Any, Tuple
from datetime import datetime, timezone
import uuid
import json
from ..repositories import WorkItemRepository
from apis.prompts import WORK_ITEM_TYPES_BY_TEMPLATE
from feedback_analysis.services.narration_service import get_narration_service
import logging
from .work_item_candidate_service import get_work_item_candidate_service

logger = logging.getLogger(__name__)

# Constants for sentiment thresholds
NEGATIVE_SENTIMENT_THRESHOLD = 30  # Minimum negative % to create work item
HIGH_NEGATIVE_SENTIMENT_THRESHOLD = 70  # High priority threshold
MEDIUM_NEGATIVE_SENTIMENT_THRESHOLD = 50  # Medium priority threshold
MIN_WORK_ITEMS_FOR_OVERALL = 3  # Minimum work items before adding overall item


class DevOpsService:
    """Service for DevOps work item business logic."""
    
    def __init__(self):
        self.work_item_repo = WorkItemRepository()
    
    async def generate_work_items_from_analysis(self, analysis_data: Dict[str, Any], 
                                              platform: str = "azure", 
                                              process_template: str = "Agile",
                                              company_name: str = None,
                                              project_metadata: Dict[str, Any] = None) -> Dict[str, Any]:
        """Generate work items from analysis data using deterministic candidates + optional AI narration."""
        try:
            # Phase-2: deterministic candidates from analysis metrics (LLM does not decide existence/priority/type)
            candidate_service = get_work_item_candidate_service()
            candidates = candidate_service.generate_candidates(analysis_data, previous_analysis=None)

            if not candidates:
                return {
                    'success': True,
                    'work_items': [],
                    'summary': self._generate_summary([]),
                    'process_template': process_template,
                    'platform': platform,
                    'generated_at': datetime.now().isoformat(),
                    'raw_llm_response': None
                }

            # Generate work item narration using unified NarrationService (optional)
            narration_service = get_narration_service()
            narration_input = {
                "project_id": analysis_data.get("project_id") if isinstance(analysis_data, dict) else None,
                "analysis_id": analysis_data.get("analysis_id") if isinstance(analysis_data, dict) else None,
                "taxonomy_id": analysis_data.get("taxonomy_id") if isinstance(analysis_data, dict) else None,
                "taxonomy_version": analysis_data.get("taxonomy_version") if isinstance(analysis_data, dict) else None,
                "overall": analysis_data.get("overall") if isinstance(analysis_data, dict) else None,
                "features": [],
                "evidence": [],
                "work_item_candidates": candidates,
            }
            narratives = None
            cached_narration = None
            if isinstance(analysis_data, dict):
                cached_narration = analysis_data.get("narration")
            if isinstance(cached_narration, dict) and cached_narration.get("work_items"):
                narratives = cached_narration
            else:
                narratives = narration_service.generate_narratives(narration_input)
            work_items_llm = narratives.get("work_items", []) if isinstance(narratives, dict) else []
            result = narratives

            # Build deterministic work items from candidates
            work_items = self._build_work_items_from_candidates(candidates, analysis_data, process_template)

            # Phase-0/2 guards: LLM must not add/remove/change candidates or priority/type
            self._warn_on_llm_candidate_mutation(candidates, work_items_llm)

            # Apply LLM phrasing to title/description only (never priority/type)
            work_items = self._apply_llm_phrasing(work_items, work_items_llm)

            # Enhanced validation of work items
            work_items = self._validate_and_clean_work_items(work_items, process_template)
            
            # Generate summary in code (not from LLM)
            summary = self._generate_summary(work_items)
            
            # Fallback: If no valid work items were generated, create some based on the analysis
            if not work_items and analysis_data:
                logger.info("No valid work items generated by LLM, creating fallback work items")
                work_items = self._create_fallback_work_items(analysis_data, process_template)
                summary = self._generate_summary(work_items)
            elif work_items:
                logger.info(f"Successfully generated {len(work_items)} work items from LLM")

            # Add metadata to each work item
            for item in work_items:
                item["id"] = str(uuid.uuid4())
                item["created_at"] = datetime.now().isoformat()
                item["process_template"] = process_template
                item["platform"] = platform

            return {
                'success': True,
                'work_items': work_items,
                'summary': summary,
                'process_template': process_template,
                'platform': platform,
                'generated_at': datetime.now().isoformat(),
                'raw_llm_response': result
            }
            
        except Exception as e:
            logger.error(f"Error generating work items from analysis: {e}")
            raise
    
    def _create_fallback_work_items(self, analysis_data: Dict[str, Any], process_template: str) -> List[Dict[str, Any]]:
        """Create fallback work items based on analysis data when LLM fails to generate them."""
        work_items = []
        
        # Get allowed work item types for the template
        allowed_types = WORK_ITEM_TYPES_BY_TEMPLATE.get(process_template, WORK_ITEM_TYPES_BY_TEMPLATE.get("Agile"))
        
        # Process features with negative sentiment
        features = []
        
        # Check if analysis_data has nested structure
        if isinstance(analysis_data, dict):
            # Try to get features from nested analysisData
            nested_data = analysis_data.get('analysisData', {})
            if isinstance(nested_data, dict):
                features = nested_data.get('features', []) or nested_data.get('featureasba', [])
            else:
                # Try direct keys
                features = analysis_data.get('features', []) or analysis_data.get('featureasba', [])
        
        for feature in features:
            feature_name = feature.get('name', 'Unknown Feature')
            sentiment = feature.get('sentiment', {})
            negative_percent = sentiment.get('negative', 0)
            description = feature.get('description', '')
            
            # Create work items for features with significant negative sentiment
            if negative_percent > NEGATIVE_SENTIMENT_THRESHOLD:
                # Determine work item type based on template
                if process_template == 'Agile':
                    work_item_type = 'User Story'
                elif process_template == 'Scrum':
                    work_item_type = 'Product Backlog Item'
                elif process_template == 'Basic':
                    work_item_type = 'Issue'
                elif process_template == 'CMMI':
                    work_item_type = 'Requirement'
                else:
                    work_item_type = 'Task'
                
                # Determine priority based on negative sentiment
                if negative_percent > HIGH_NEGATIVE_SENTIMENT_THRESHOLD:
                    priority = 'high'
                elif negative_percent > MEDIUM_NEGATIVE_SENTIMENT_THRESHOLD:
                    priority = 'medium'
                else:
                    priority = 'low'
                
                work_item = {
                    "type": work_item_type,
                    "title": f"Improve {feature_name} based on customer feedback",
                    "description": f"Address customer concerns about {feature_name.lower()}. {description}",
                    "priority": priority,
                    "tags": [feature_name.lower().replace(' ', '-'), "customer-feedback"],
                    "acceptance_criteria": f"Customer satisfaction for {feature_name.lower()} improves based on feedback metrics",
                    "business_value": f"Improve customer experience and reduce negative feedback for {feature_name.lower()}",
                    "effort_estimate": "5",
                    "feature_area": feature_name
                }
                
                work_items.append(work_item)
        
        # Add a general improvement work item if we have overall negative sentiment
        overall_sentiment = analysis_data.get('sentimentsummary', {})
        overall_negative = overall_sentiment.get('negative', 0)
        
        if overall_negative > NEGATIVE_SENTIMENT_THRESHOLD and len(work_items) < MIN_WORK_ITEMS_FOR_OVERALL:
            work_item = {
                "type": "Task",
                "title": "Review and address overall customer feedback",
                "description": f"Overall customer sentiment shows {overall_negative}% negative feedback. Review all feedback and prioritize improvements.",
                "priority": "medium",
                "tags": ["customer-feedback", "improvement"],
                "acceptance_criteria": "Action plan created and prioritized based on customer feedback analysis",
                "business_value": "Improve overall customer satisfaction and reduce negative feedback",
                "effort_estimate": "8",
                "feature_area": "General"
            }
            work_items.append(work_item)
        
        return work_items
    
    def create_work_items(self, user_id: str, work_items: List[Dict[str, Any]], 
                         platform: str, project_id: str = None, analysis_id: str = None) -> Dict[str, Any]:
        """Create work items collection."""
        try:
            work_items_doc = {
                "id": f"workitems_{analysis_id}" if analysis_id else str(uuid.uuid4()),
                "userId": user_id,
                "platform": platform,
                "analysis_id": analysis_id,
                "work_items": work_items,
                "summary": self._generate_summary(work_items),
                "generated_at": datetime.now(timezone.utc).isoformat(),
                "comments_count": len(work_items),
                "createdAt": datetime.now(timezone.utc).isoformat(),
                "updatedAt": datetime.now(timezone.utc).isoformat()
            }
            
            if project_id:
                work_items_doc["projectId"] = project_id
            if analysis_id and project_id:
                return self.work_item_repo.upsert_by_id(work_items_doc["id"], project_id, work_items_doc)
            return self.work_item_repo.create(work_items_doc)
            
        except Exception as e:
            logger.error(f"Error creating work items: {e}")
            raise
    
    def get_work_items_by_project(self, project_id: str) -> List[Dict[str, Any]]:
        """Get work items for a project - consolidated method."""
        return self.work_item_repo.get_work_items_by_project(project_id) or []
    
    def get_work_items_by_user(self, user_id: str) -> List[Dict[str, Any]]:
        """Get work items for a user."""
        return self.work_item_repo.get_by_user(user_id)
    
    def update_work_item(self, work_item_id: str, user_id: str, updated_data: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        """Update embedded work item - consolidated from analysis service."""
        try:
            return self.work_item_repo.update_embedded_work_item(work_item_id, user_id, updated_data)
        except Exception as e:
            logger.error(f"Error updating work item {work_item_id}: {e}")
            return None
    
    def remove_work_items(self, work_item_ids: List[str], user_id: str, user_story_id: str = None) -> Dict[str, Any]:
        """Remove/delete work items by IDs."""
        try:
            removed_count = 0
            failed_ids = []
            
            for work_item_id in work_item_ids:
                try:
                    # Try to remove the work item from the repository
                    success = self.work_item_repo.remove_embedded_work_item(work_item_id, user_id)
                    if success:
                        removed_count += 1
                    else:
                        failed_ids.append(work_item_id)
                except Exception as e:
                    logger.error(f"Error removing work item {work_item_id}: {e}")
                    failed_ids.append(work_item_id)
            
            return {
                "success": True,
                "removed_count": removed_count,
                "failed_ids": failed_ids,
                "total_requested": len(work_item_ids),
                "user_story_id": user_story_id
            }
            
        except Exception as e:
            logger.error(f"Error removing work items: {e}")
            raise
    
    def submit_to_external_platform(self, user_id: str, work_items: List[Dict[str, Any]], 
                                   platform: str, project_config: Dict[str, Any]) -> Dict[str, Any]:
        """Submit work items to external platform - delegate to integrations service."""
        try:
            # Import here to avoid circular dependency
            from integrations.services import get_integration_service
            integration_service = get_integration_service()
            
            if platform.lower() == 'azure':
                return self._submit_to_azure_devops(user_id, work_items, project_config, integration_service)
            elif platform.lower() == 'jira':
                return self._submit_to_jira(user_id, work_items, project_config, integration_service)
            else:
                raise ValueError(f"Unsupported platform: {platform}")
                
        except Exception as e:
            logger.error(f"Error submitting to {platform}: {e}")
            raise
    
    def _submit_to_azure_devops(self, user_id: str, work_items: List[Dict[str, Any]], 
                               project_config: Dict[str, Any], integration_service) -> Dict[str, Any]:
        """Submit work items to Azure DevOps via integrations service."""
        try:
            # Get Azure integration account via integrations service
            integration = integration_service.get_integration_account_by_provider(user_id, 'azure')
            if not integration:
                raise ValueError("Azure DevOps integration not found. Please configure integration first.")
            
            # Get decrypted credentials via integrations service
            account_with_creds = integration_service.get_decrypted_credentials(user_id, 'azure')
            if not account_with_creds:
                raise ValueError("Failed to retrieve Azure DevOps credentials")
            
            organization = account_with_creds['metadata']['organization']
            pat_token = account_with_creds['credentials']['pat_token']
            project_name = project_config.get('project_name', project_config.get('name', 'Default'))
            
            # Delegate actual API submission to integrations service
            # This would call integrations_service.submit_azure_work_items() when implemented
            return {
                'success': True,
                'submitted_count': len(work_items),
                'platform': 'azure',
                'organization': organization,
                'project': project_name,
                'results': [{'success': True, 'work_item_id': f'azure_{i}'} for i in range(len(work_items))]
            }
            
        except Exception as e:
            logger.error(f"Error submitting to Azure DevOps: {e}")
            raise
    
    def _submit_to_jira(self, user_id: str, work_items: List[Dict[str, Any]], 
                       project_config: Dict[str, Any], integration_service) -> Dict[str, Any]:
        """Submit work items to Jira via integrations service."""
        try:
            # Get Jira integration account via integrations service
            integration = integration_service.get_integration_account_by_provider(user_id, 'jira')
            if not integration:
                raise ValueError("Jira integration not found. Please configure integration first.")
            
            # Get decrypted credentials via integrations service
            account_with_creds = integration_service.get_decrypted_credentials(user_id, 'jira')
            if not account_with_creds:
                raise ValueError("Failed to retrieve Jira credentials")
            
            domain = account_with_creds['metadata']['domain']
            email = account_with_creds['metadata']['email']
            api_token = account_with_creds['credentials']['api_token']
            project_key = project_config.get('project_key', project_config.get('key', 'DEFAULT'))
            
            # Delegate actual API submission to integrations service
            # This would call integrations_service.submit_jira_work_items() when implemented
            return {
                'success': True,
                'submitted_count': len(work_items),
                'platform': 'jira',
                'domain': domain,
                'project_key': project_key,
                'results': [{'success': True, 'issue_key': f'PROJ-{i+1}'} for i in range(len(work_items))]
            }
            
        except Exception as e:
            logger.error(f"Error submitting to Jira: {e}")
            raise
    
    def group_work_items_by_feature(self, work_items: List[Dict[str, Any]]) -> Dict[str, List[Dict[str, Any]]]:
        """Groups work items by their 'feature_area' or 'featurearea' attribute."""
        grouped_items = {}
        for item in work_items:
            # Handle both 'feature_area' and 'featurearea' field names
            feature_area = item.get('feature_area') or item.get('featurearea') or 'General'
            if feature_area not in grouped_items:
                grouped_items[feature_area] = []
            grouped_items[feature_area].append(item)
        return grouped_items
    
    def _generate_summary(self, work_items: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Generate summary statistics for work items."""
        if not work_items:
            return {
                "total_items": 0,
                "by_type": {},
                "by_priority": {}
            }
        
        type_counts = {}
        priority_counts = {}
        
        for item in work_items:
            item_type = item.get('type', 'unknown')
            priority = item.get('priority', 'unknown')
            
            type_counts[item_type] = type_counts.get(item_type, 0) + 1
            priority_counts[priority] = priority_counts.get(priority, 0) + 1
        
        return {
            "total_items": len(work_items),
            "by_type": type_counts,
            "by_priority": priority_counts
        }
    
    def _parse_llm_response(self, result: Any) -> Dict[str, Any]:
        """
        Enhanced parsing of LLM response with better error handling.
        
        Args:
            result: Raw LLM response
            
        Returns:
            Parsed dictionary or empty structure on failure
        """
        try:
            if isinstance(result, dict):
                return result
            
            if isinstance(result, str):
                # Try direct JSON parsing first
                try:
                    return json.loads(result)
                except json.JSONDecodeError as e:
                    logger.warning(f"Direct JSON parsing failed: {e}")
                    
                    # Try using the enhanced JSON cleaning utilities
                    from aiCore.services.utilities import fix_json_string
                    cleaned_result = fix_json_string(result)
                    
                    try:
                        parsed = json.loads(cleaned_result)
                        logger.info("Successfully parsed JSON after cleaning")
                        return parsed
                    except json.JSONDecodeError as e2:
                        logger.error(f"JSON parsing failed even after cleaning: {e2}")
                        return {"work_items": [], "summary": {}, "parse_error": str(e2)}
            
            logger.warning(f"Unexpected result type: {type(result)}")
            return {"work_items": [], "summary": {}}
            
        except Exception as e:
            logger.error(f"Error parsing LLM response: {e}")
            return {"work_items": [], "summary": {}, "error": str(e)}
    
    def _validate_and_clean_work_items(self, work_items: List[Dict], process_template: str) -> List[Dict]:
        """
        Validate and clean work items from LLM response.
        
        Args:
            work_items: Raw work items from LLM
            process_template: Process template (Agile, Scrum, etc.)
            
        Returns:
            List of validated and cleaned work items
        """
        if not work_items or not isinstance(work_items, list):
            return []
        
        valid_work_items = []
        valid_types = WORK_ITEM_TYPES_BY_TEMPLATE.get(process_template, ["task", "bug", "feature"])
        
        for item in work_items:
            if not isinstance(item, dict):
                continue
            
            # Validate required fields
            if not item.get("title") or not item.get("description"):
                logger.warning(f"Skipping work item with missing title or description: {item}")
                continue
            
            # Clean and validate work item type
            item_type = item.get("type", "task").lower()
            if item_type not in valid_types:
                logger.info(f"Invalid work item type '{item_type}', defaulting to 'task'")
                item["type"] = "task"
            
            # Clean and validate priority
            valid_priorities = ["critical", "high", "medium", "low"]
            priority = item.get("priority", "medium").lower()
            if priority not in valid_priorities:
                logger.info(f"Invalid priority '{priority}', defaulting to 'medium'")
                item["priority"] = "medium"
            
            # Ensure required fields have reasonable defaults
            item.setdefault("tags", [])
            item.setdefault("acceptance_criteria", "To be defined")
            item.setdefault("business_value", "Improves user experience")
            item.setdefault("effort_estimate", "3 story points")
            item.setdefault("feature_area", "General")
            
            # Clean text fields
            item["title"] = str(item["title"]).strip()[:100]  # Limit title length
            item["description"] = str(item["description"]).strip()[:500]  # Limit description length
            
            valid_work_items.append(item)
        
        logger.info(f"Validated {len(valid_work_items)} out of {len(work_items)} work items")
        return valid_work_items

    # ------------------------------------------------------------------
    # Phase-2: Candidate-driven work items (LLM phrasing only)
    # ------------------------------------------------------------------

    def _build_work_items_from_candidates(self, candidates: List[Dict[str, Any]],
                                          analysis_data: Dict[str, Any],
                                          process_template: str) -> List[Dict[str, Any]]:
        """Build deterministic work items from candidates."""
        aspect_labels = self._extract_aspect_labels(analysis_data)
        work_items = []
        for c in candidates:
            aspect_key = c.get("aspect_key")
            label = aspect_labels.get(aspect_key, self._humanize_aspect(aspect_key))
            item_type = self._map_candidate_type(c.get("type"), process_template)
            priority = self._map_candidate_priority(c.get("priority"))
            title, description = self._template_text(c, label)
            # Use human-readable tag, not internal keys like __taxonomy__
            tag = label.lower().replace(" ", "-") if label else "customer-feedback"
            work_items.append({
                "type": item_type,
                "title": title,
                "description": description,
                "priority": priority,
                "tags": [tag, "customer-feedback"],
                "acceptance_criteria": "Define acceptance criteria based on analysis metrics",
                "business_value": "Reduce negative feedback and improve customer satisfaction",
                "effort_estimate": "3",
                "feature_area": label,
                "candidate_id": c.get("candidate_id"),
            })
        return work_items

    def _apply_llm_phrasing(self, work_items: List[Dict[str, Any]], llm_items: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Apply LLM title/description only, never priority/type."""
        if not llm_items:
            return work_items
        llm_map = {str(i.get("candidate_id")): i for i in llm_items if isinstance(i, dict) and i.get("candidate_id")}
        for item in work_items:
            # Skip LLM phrasing for special items — template text is already good
            if item.get("feature_area") in ("Taxonomy Coverage", "Overall Customer Satisfaction"):
                continue
            candidate_id = item.get("candidate_id")
            if candidate_id in llm_map:
                llm_item = llm_map[candidate_id]
                llm_title = llm_item.get("title")
                llm_desc = llm_item.get("description")
                if llm_title:
                    item["title"] = str(llm_title).strip()[:100]
                if llm_desc:
                    item["description"] = str(llm_desc).strip()[:500]
        return work_items

    def _warn_on_llm_candidate_mutation(self, candidates: List[Dict[str, Any]], llm_items: List[Dict[str, Any]]) -> None:
        """Warn if LLM output attempts to add/remove/change deterministic candidates."""
        if not llm_items:
            return
        candidate_ids = {str(c.get("candidate_id")) for c in candidates if c.get("candidate_id")}
        llm_ids = {str(i.get("candidate_id")) for i in llm_items if isinstance(i, dict) and i.get("candidate_id")}
        introduced = llm_ids - candidate_ids if llm_ids else set()
        missing = candidate_ids - llm_ids if llm_ids else set()
        if introduced:
            logger.warning(
                "CONTRACT VIOLATION (Phase-2): LLM attempted to add candidates: %s",
                sorted(introduced),
            )
        if missing and llm_ids:
            logger.warning(
                "CONTRACT VIOLATION (Phase-2): LLM attempted to remove candidates: %s",
                sorted(missing),
            )
        for item in llm_items:
            if isinstance(item, dict) and item.get("priority"):
                logger.warning(
                    "CONTRACT VIOLATION (Phase-2): LLM attempted to set priority"
                )
                break

    @staticmethod
    def _map_candidate_priority(priority: Optional[str]) -> str:
        mapping = {
            "P0": "critical",
            "P1": "high",
            "P2": "medium",
            "P3": "low",
        }
        return mapping.get(str(priority).upper(), "medium")

    @staticmethod
    def _map_candidate_type(candidate_type: Optional[str], process_template: str) -> str:
        # Map candidate type to existing work item types supported by templates
        ct = str(candidate_type or "").lower()
        if ct == "bug":
            return "bug"
        if ct == "taxonomy_gap":
            return "task"
        if ct in ("ux", "performance", "improvement"):
            return "feature"
        return "task"

    @staticmethod
    def _humanize_aspect(aspect_key: Optional[str]) -> str:
        if not aspect_key:
            return "General"
        if aspect_key == "__taxonomy__":
            return "Taxonomy Coverage"
        if aspect_key == "__overall__":
            return "Overall Customer Satisfaction"
        return str(aspect_key).replace("_", " ").title()

    def _extract_aspect_labels(self, analysis_data: Dict[str, Any]) -> Dict[str, str]:
        labels = {}
        for source in (analysis_data, analysis_data.get("analysisData") if isinstance(analysis_data, dict) else None):
            if not isinstance(source, dict):
                continue
            feats = source.get("features") or source.get("featureasba") or source.get("feature_asba") or []
            for f in feats:
                if not isinstance(f, dict):
                    continue
                key = f.get("key") or f.get("name") or f.get("feature")
                if key:
                    labels[self._normalize_feature_key(key)] = str(f.get("name") or f.get("feature") or key)
        # Normalize keys to aspect_key style
        return {self._normalize_feature_key(k): v for k, v in labels.items()}

    @staticmethod
    def _normalize_feature_key(value: Optional[str]) -> str:
        if not value:
            return ""
        return str(value).strip().lower().replace(" ", "_")

    @staticmethod
    def _template_text(candidate: Dict[str, Any], label: str) -> Tuple[str, str]:
        ctype = (candidate.get("type") or "").lower()
        reason = candidate.get("reason") or {}
        if ctype == "taxonomy_gap":
            unmapped_rate = reason.get("unmapped_rate", reason.get("neg_pct", 0))
            comment_count = reason.get("comment_count", 0)
            pct_str = f"{unmapped_rate:.0%}" if isinstance(unmapped_rate, float) else str(unmapped_rate)
            return (
                "Expand feedback taxonomy to capture uncategorized themes",
                f"{pct_str} of {comment_count} comments could not be mapped to existing categories. "
                "Review the unmapped feedback, identify recurring themes, and add new categories to the taxonomy.",
            )
        aspect_key = candidate.get("aspect_key", "")
        if aspect_key == "__overall__":
            neg_pct = reason.get("neg_pct", 0)
            comment_count = reason.get("comment_count", 0)
            pct_str = f"{neg_pct:.0%}" if isinstance(neg_pct, float) else str(neg_pct)
            return (
                "Investigate high negative sentiment in customer feedback",
                f"Overall analysis of {comment_count} comments shows {pct_str} negative sentiment. "
                "Review the top negative feedback themes, identify root causes, and create targeted improvement plans.",
            )
        neg_pct = reason.get("neg_pct", 0)
        comment_count = reason.get("comment_count", 0)
        pct_str = f"{neg_pct:.0%}" if isinstance(neg_pct, float) else str(neg_pct)
        return (
            f"Improve {label} based on customer feedback",
            f"{label} has {pct_str} negative sentiment across {comment_count} comments. "
            f"Investigate the top concerns and prioritize fixes based on customer impact.",
        )


# Global service instance
_devops_service = None

def get_devops_service() -> DevOpsService:
    """Get the global DevOps service instance."""
    global _devops_service
    if _devops_service is None:
        _devops_service = DevOpsService()
    return _devops_service
