# Generated by Django 4.2.20 on 2026-03-27 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=128, unique=True)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=128, unique=True)),
                ('stripe_price_id', models.CharField(blank=True, default='', max_length=128)),
                ('subscription_status', models.CharField(db_index=True, default='inactive', max_length=32)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('livemode', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'billing_profiles',
            },
        ),
        migrations.CreateModel(
            name='BillingWebhookEvent',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stripe_event_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=128)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('livemode', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'billing_webhook_events',
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('period', models.CharField(db_index=True, help_text='YYYY-MM period key, e.g. 2026-03', max_length=7)),
                ('analysis_count', models.PositiveIntegerField(default=0)),
                ('work_item_gen_count', models.PositiveIntegerField(default=0)),
                ('llm_tokens_used', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'db_table': 'billing_usage_records',
                'indexes': [models.Index(fields=['user_id', 'period'], name='billing_usa_user_id_e84451_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='usagerecord',
            constraint=models.UniqueConstraint(fields=('user_id', 'period'), name='uq_usage_user_period'),
        ),
        migrations.AddIndex(
            model_name='billingwebhookevent',
            index=models.Index(fields=['event_type'], name='billing_web_event_t_d567de_idx'),
        ),
        migrations.AddIndex(
            model_name='billingwebhookevent',
            index=models.Index(fields=['processed'], name='billing_web_process_177aea_idx'),
        ),
        migrations.AddIndex(
            model_name='billingwebhookevent',
            index=models.Index(fields=['created_at'], name='billing_web_created_f6178e_idx'),
        ),
        migrations.AddIndex(
            model_name='billingprofile',
            index=models.Index(fields=['user_id'], name='billing_pro_user_id_058145_idx'),
        ),
        migrations.AddIndex(
            model_name='billingprofile',
            index=models.Index(fields=['stripe_customer_id'], name='billing_pro_stripe__d808dc_idx'),
        ),
        migrations.AddIndex(
            model_name='billingprofile',
            index=models.Index(fields=['stripe_subscription_id'], name='billing_pro_stripe__174004_idx'),
        ),
        migrations.AddIndex(
            model_name='billingprofile',
            index=models.Index(fields=['subscription_status'], name='billing_pro_subscri_1be656_idx'),
        ),
    ]
