# Generated by Django 4.2.20 on 2026-03-27 10:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_add_work_item_candidate_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(db_index=True, default='active', max_length=32)),
                ('external_links', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_analysis_id', models.CharField(blank=True, default='', max_length=128)),
                ('last_analyzed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='authentication.useraccount')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('provider', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(db_index=True, default='active', max_length=32)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_states', to='authentication.useraccount')),
            ],
            options={
                'db_table': 'oauth_states',
            },
        ),
        migrations.CreateModel(
            name='IntegrationAccount',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('provider', models.CharField(db_index=True, max_length=64)),
                ('type', models.CharField(db_index=True, default='integration_account', max_length=64)),
                ('account_name', models.CharField(blank=True, default='', max_length=255)),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_accounts', to='authentication.useraccount')),
            ],
            options={
                'db_table': 'integrations',
            },
        ),
        migrations.CreateModel(
            name='FeedbackSource',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(db_index=True, default='feedbackSource', max_length=64)),
                ('provider', models.CharField(db_index=True, max_length=64)),
                ('account_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(db_index=True, default='active', max_length=32)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_sources', to='integrations.project')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_sources', to='authentication.useraccount')),
            ],
            options={
                'db_table': 'feedback_sources',
            },
        ),
        migrations.CreateModel(
            name='SlackFeedbackItem',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('source_id', models.CharField(db_index=True, max_length=255)),
                ('comment', models.TextField(blank=True, default='')),
                ('source_channel', models.CharField(blank=True, default='', max_length=255)),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('feedback_created_at', models.CharField(blank=True, default='', max_length=64)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slack_feedback_items', to='integrations.project')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slack_feedback_items', to='authentication.useraccount')),
            ],
            options={
                'db_table': 'slack_feedback_items',
                'indexes': [models.Index(fields=['project', 'source_id'], name='slack_feedb_project_579a10_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('role', models.CharField(db_index=True, max_length=32)),
                ('actor_id', models.CharField(blank=True, default='', max_length=64)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_roles', to='integrations.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_roles', to='authentication.useraccount')),
            ],
            options={
                'db_table': 'project_roles',
                'indexes': [models.Index(fields=['project', 'role'], name='project_rol_project_019c60_idx'), models.Index(fields=['user', 'role'], name='project_rol_user_id_3713b5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='projectrole',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='uq_project_user_role'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'created_at'], name='projects_user_id_259761_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_status_6303d7_idx'),
        ),
        migrations.AddIndex(
            model_name='oauthstate',
            index=models.Index(fields=['provider', 'status', 'created_at'], name='oauth_state_provide_89615c_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationaccount',
            index=models.Index(fields=['provider', 'created_at'], name='integration_provide_ec0335_idx'),
        ),
        migrations.AddConstraint(
            model_name='integrationaccount',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='uq_integration_user_provider'),
        ),
        migrations.AddIndex(
            model_name='feedbacksource',
            index=models.Index(fields=['provider', 'status', 'created_at'], name='feedback_so_provide_87abe2_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacksource',
            index=models.Index(fields=['project', 'created_at'], name='feedback_so_project_794e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacksource',
            index=models.Index(fields=['user', 'created_at'], name='feedback_so_user_id_2ae10f_idx'),
        ),
    ]
