# Generated by Django 4.2.20 on 2026-05-02 00:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_add_work_item_candidate_table'),
        ('integrations', '0001_add_work_item_candidate_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('role', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(db_index=True, default='active', max_length=32)),
                ('actor_id', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'organization_memberships',
            },
        ),
        migrations.RemoveConstraint(
            model_name='integrationaccount',
            name='uq_integration_user_provider',
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='integrations.organization'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to='authentication.useraccount'),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to='authentication.useraccount'),
        ),
        migrations.AddField(
            model_name='feedbacksource',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_sources', to='integrations.organization'),
        ),
        migrations.AddField(
            model_name='integrationaccount',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_accounts', to='integrations.organization'),
        ),
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='integrations.organization'),
        ),
        migrations.AddField(
            model_name='slackfeedbackitem',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slack_feedback_items', to='integrations.organization'),
        ),
        migrations.AddIndex(
            model_name='feedbacksource',
            index=models.Index(fields=['organization', 'created_at'], name='feedback_so_organiz_d75de5_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationaccount',
            index=models.Index(fields=['organization', 'created_at'], name='integration_organiz_23fd5b_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'created_at'], name='projects_organiz_10366f_idx'),
        ),
        migrations.AddIndex(
            model_name='slackfeedbackitem',
            index=models.Index(fields=['organization', 'source_id'], name='slack_feedb_organiz_4e784f_idx'),
        ),
        migrations.AddConstraint(
            model_name='integrationaccount',
            constraint=models.UniqueConstraint(fields=('organization', 'provider'), name='uq_integration_org_provider'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['organization', 'role'], name='organizatio_organiz_25ae86_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['user', 'role'], name='organizatio_user_id_63960f_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['status'], name='organizatio_status_6e78b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='uq_organization_user_membership'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug'], name='organizatio_slug_5b8b37_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['created_at'], name='organizatio_created_8a4b5e_idx'),
        ),
    ]
