# Generated by Django 4.2.20 on 2026-05-02 00:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_add_work_item_candidate_table'),
        ('integrations', '0002_organization_organizationmembership_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptOverride',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('scope', models.CharField(db_index=True, max_length=32)),
                ('prompt_type', models.CharField(db_index=True, max_length=64)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_overrides', to='integrations.organization')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_prompt_overrides', to='authentication.useraccount')),
            ],
            options={
                'db_table': 'prompt_overrides',
                'indexes': [models.Index(fields=['scope', 'prompt_type'], name='prompt_over_scope_6769ad_idx'), models.Index(fields=['organization', 'prompt_type'], name='prompt_over_organiz_1f5ac7_idx'), models.Index(fields=['is_active'], name='prompt_over_is_acti_8a57e6_idx')],
            },
        ),
    ]
