# Generated by Django 4.2.20 on 2026-03-27 10:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_add_work_item_candidate_table'),
        ('integrations', '0001_add_work_item_candidate_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('type', models.CharField(db_index=True, default='user_story', max_length=64)),
                ('status', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('work_items', models.JSONField(blank=True, default=list)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integrations.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.useraccount')),
            ],
            options={
                'db_table': 'user_stories',
            },
        ),
        migrations.CreateModel(
            name='WorkItemQualityRule',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('type', models.CharField(db_index=True, default='work_item_quality_rule', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.project')),
            ],
            options={
                'db_table': 'work_item_quality_rules',
            },
        ),
        migrations.CreateModel(
            name='WorkItemCandidate',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('type', models.CharField(default='task', max_length=64)),
                ('priority', models.CharField(default='medium', max_length=32)),
                ('feature_area', models.CharField(blank=True, default='', max_length=256)),
                ('acceptance_criteria', models.TextField(blank=True, default='')),
                ('business_value', models.TextField(blank=True, default='')),
                ('effort_estimate', models.CharField(blank=True, default='', max_length=64)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('candidate_id', models.CharField(blank=True, default='', max_length=256)),
                ('aspect_key', models.CharField(blank=True, default='', max_length=256)),
                ('analysis_id', models.CharField(blank=True, default='', max_length=256)),
                ('platform', models.CharField(blank=True, default='', max_length=64)),
                ('process_template', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(db_index=True, default='pending', max_length=32)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('status_changed_by', models.CharField(blank=True, default='', max_length=128)),
                ('dismiss_reason', models.CharField(blank=True, default='', max_length=64)),
                ('snooze_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('merged_into', models.CharField(blank=True, default='', max_length=128)),
                ('push_status', models.CharField(db_index=True, default='not_pushed', max_length=32)),
                ('external_id', models.CharField(blank=True, default='', max_length=256)),
                ('external_url', models.URLField(blank=True, default='', max_length=1024)),
                ('external_platform', models.CharField(blank=True, default='', max_length=64)),
                ('push_error', models.TextField(blank=True, default='')),
                ('pushed_at', models.DateTimeField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.project')),
                ('user_story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='work_items.userstory')),
            ],
            options={
                'db_table': 'work_item_candidates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='workitemqualityrule',
            constraint=models.UniqueConstraint(fields=('project',), name='uq_work_item_quality_rule_project'),
        ),
        migrations.AddIndex(
            model_name='workitemcandidate',
            index=models.Index(fields=['project', 'status', '-created_at'], name='work_item_c_project_48c3f1_idx'),
        ),
        migrations.AddIndex(
            model_name='workitemcandidate',
            index=models.Index(fields=['project', '-created_at'], name='work_item_c_project_3e71cf_idx'),
        ),
        migrations.AddIndex(
            model_name='workitemcandidate',
            index=models.Index(fields=['status', 'snooze_until'], name='work_item_c_status_b1bb70_idx'),
        ),
        migrations.AddIndex(
            model_name='workitemcandidate',
            index=models.Index(fields=['user_story', 'status'], name='work_item_c_user_st_b6dfb5_idx'),
        ),
        migrations.AddIndex(
            model_name='userstory',
            index=models.Index(fields=['project', 'created_at'], name='user_storie_project_fb5dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='userstory',
            index=models.Index(fields=['user', 'created_at'], name='user_storie_user_id_6b2a67_idx'),
        ),
        migrations.AddIndex(
            model_name='userstory',
            index=models.Index(fields=['type', 'generated_at'], name='user_storie_type_dca1b5_idx'),
        ),
    ]
