"""
Django settings for apis project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Ensure the logs directory exists before LOGGING handlers try to write files
os.makedirs(BASE_DIR / 'logs', exist_ok=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-your-secret-key-here-change-in-production')
DEBUG = True

ALLOWED_HOSTS = ['.azurewebsites.net', '*', '127.0.0.1', 'localhost']

APPLICATIONINSIGHTS_CONNECTION_STRING = os.getenv(
    'APPLICATIONINSIGHTS_CONNECTION_STRING',
    'InstrumentationKey=00000000-0000-0000-0000-000000000000'
)

# Only initialize OpenTelemetry if connection string is configured
# Disabled for development - uncomment for production
# if APPLICATIONINSIGHTS_CONNECTION_STRING and not APPLICATIONINSIGHTS_CONNECTION_STRING.endswith('00000000-0000-0000-0000-000000000000'):
#     OPENTELEMETRY_DJANGO = {
#         'SERVICE_NAME': os.getenv('WEBSITE_SITE_NAME', 'django-app'),
#         'TRACES_EXPORTER': 'azure_monitor',
#         'METRICS_EXPORTER': 'azure_monitor',
#         'LOGS_EXPORTER': 'azure_monitor',
#     }

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'detailed': {
            'format': '{levelname} {asctime} {name} {module} {funcName} {lineno} {message}',
            'style': '{',
        },
        'json': {
            '()': 'apis.logging_formatters.JsonFormatter',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'detailed',
            'filters': ['trace_context'],
        },
        'app_file': {
            'level': 'DEBUG',
            'class': 'apis.logging_handlers.DatedSubdirTimedRotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'json',
            'when': 'midnight',
            'interval': 1,
            'backupCount': 14,
            'encoding': 'utf-8',
            'utc': True,
            'delay': True,
            'filters': ['trace_context'],
        },
        'access_file': {
            'level': 'INFO',
            'class': 'apis.logging_handlers.DatedSubdirTimedRotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'access.log',
            'formatter': 'json',
            'when': 'midnight',
            'interval': 1,
            'backupCount': 14,
            'encoding': 'utf-8',
            'utc': True,
            'delay': True,
            'filters': ['trace_context'],
        },
        'azure_logs': {
            'level': 'INFO',
            'class': 'apis.logging_azure.LogAnalyticsHandler',
            'formatter': 'json',
            'filters': ['trace_context'],
        },
    },
    'filters': {
        'trace_context': {
            '()': 'apis.logging_filters.TraceContextFilter',
        }
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'app_file', 'azure_logs'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'app_file', 'azure_logs'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console', 'app_file', 'azure_logs'],
            'level': 'INFO',
            'propagate': False,
        },
        'saramsa-dev': {
            'handlers': ['console', 'app_file', 'azure_logs'],
            'level': 'INFO',
            'propagate': False,
        },
        'apis.middleware': {
            'handlers': ['console', 'access_file', 'azure_logs'],
            'level': 'INFO',
            'propagate': False,
        },
        'apis.security': {
            'handlers': ['console', 'app_file', 'azure_logs'],
            'level': 'INFO',
            'propagate': False,
        },
        'apis.otel': {
            'handlers': ['console', 'app_file', 'azure_logs'],
            'level': 'INFO',
            'propagate': False,
        },
        # OpenTelemetry loggers
        'opentelemetry': {
            'handlers': ['console', 'app_file', 'azure_logs'],
            'level': 'INFO',
            'propagate': False,
        },
        'azure.monitor': {
            'handlers': ['console', 'app_file', 'azure_logs'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'app_file'],
        'level': 'INFO',
    },
}

# Cosmos DB Configuration
COSMOS_DB_CONFIG = {
    'endpoint': os.getenv('COSMOS_DB_ENDPOINT', 'https://your-cosmos-account.documents.azure.com:443/'),
    'key': os.getenv('COSMOS_DB_KEY', 'your-cosmos-db-key'),
    'database_name': os.getenv('COSMOS_DB_DATABASE', 'saramsa-db'),
    'containers': {
        'users': os.getenv('COSMOS_DB_USERS_CONTAINER', 'users'),
        'analysis': os.getenv('COSMOS_DB_ANALYSIS_CONTAINER', 'analysis'),
        'uploads': os.getenv('COSMOS_DB_UPLOADS_CONTAINER', 'uploads'),
        'user_stories': os.getenv('COSMOS_DB_USER_STORIES_CONTAINER', 'user_stories'),
        'projects': os.getenv('COSMOS_DB_PROJECTS_CONTAINER', 'projects'),
        'user_data': os.getenv('COSMOS_DB_USER_DATA_CONTAINER', 'user_data'),
        'integrations': os.getenv('COSMOS_DB_INTEGRATIONS_CONTAINER', 'integrations'),
    }
}

# Cosmos DB Only - No SQLite needed
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.sessions',
    'django.contrib.auth',  
    'django.contrib.contenttypes', 
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'insightsGenerator',
    'uploadFile',
    'corsheaders',
    'authapp',
    'integrations',
    'rest_framework_simplejwt.token_blacklist'
]

# Custom authentication backend for Cosmos DB
AUTHENTICATION_BACKENDS = [
    'authapp.authentication.CosmosDBAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',  # Fallback
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Custom logging middleware
    'apis.middleware.RequestResponseLoggingMiddleware',
    'apis.middleware.PerformanceMonitoringMiddleware',
    'apis.middleware.SecurityLoggingMiddleware',
]

ROOT_URLCONF = 'apis.urls'
APPEND_SLASH = False

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
            ],
        },
    },
]

WSGI_APPLICATION = 'apis.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = False

# Optional: Allow cookies (if using session/auth)
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    'https://gray-sea-02102141e.3.azurestaticapps.net',
    'http://localhost:3000',      
    'http://localhost:8000',   
]

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
]

CORS_ALLOW_HEADERS = [
    'Accept',
    'Content-Type',
    'Authorization',
    'X-Requested-With',
    'X-CSRFToken',
    'Origin',
    'Referer',
]

# Trust requests coming from the static frontend domain (needed for some POSTs)
CSRF_TRUSTED_ORIGINS = [
    'https://saramsa-backend-c4g2e4fbfqeuhehm.centralus-01.azurewebsites.net/',
    'http://localhost:3000',
    'http://localhost:8000',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'authapp.authentication.CosmosDBJWTAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Fallback
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SIMPLE_JWT = {
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),  # 1 hour access token
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),    # Longer-lived refresh token
    'AUTH_HEADER_TYPES': ('Bearer',),
    'UPDATE_LAST_LOGIN': True,
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(hours=1),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),
}


# Azure DevOps Configuration - Required for production
AZURE_DEVOPS_ORGANIZATION = os.getenv('AZURE_DEVOPS_ORGANIZATION')
AZURE_DEVOPS_PROJECT = os.getenv('AZURE_DEVOPS_PROJECT')
AZURE_DEVOPS_PAT = os.getenv('AZURE_DEVOPS_PAT')

# Jira Configuration - Optional, but required if using Jira
JIRA_EMAIL = os.getenv('JIRA_EMAIL')
JIRA_API_TOKEN = os.getenv('JIRA_API_TOKEN')
JIRA_PROJECT_KEY = os.getenv('JIRA_PROJECT_KEY')
JIRA_DOMAIN = os.getenv('JIRA_DOMAIN')

# Swagger/OpenAPI Configuration
SPECTACULAR_SETTINGS = {
    'TITLE': 'Saramsa API',
    'DESCRIPTION': 'API documentation for Saramsa application',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/',
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
    },
    'SECURITY': [
        {
            'Bearer': []
        }
    ],
    'TAGS': [
        {'name': 'auth', 'description': 'Authentication endpoints'},
        {'name': 'insights', 'description': 'Insights generation endpoints'},
        {'name': 'workitems', 'description': 'DevOps work items endpoints'},
        {'name': 'upload', 'description': 'File upload endpoints'},
    ],
}