name: Saramsa-Be CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/saramsa-backend.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          
      - name: Install dependencies
        run: |
          cd backend
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Django migrations and collect static files
        run: |
          cd backend
          source venv/bin/activate
          python manage.py migrate --noinput
          python manage.py collectstatic --noinput
        env:
          DJANGO_SETTINGS_MODULE: apis.settings
          API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          ENDPOINT_URL: ${{ secrets.AZURE_OPENAI_ENDPOINT_URL }}
          DEPLOYMENT_NAME: ${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME }}
          API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
          AZURE_DEVOPS_ORGANIZATION: ${{ secrets.AZURE_DEVOPS_ORGANIZATION }}
          AZURE_DEVOPS_PROJECT: ${{ secrets.AZURE_DEVOPS_PROJECT }}
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      # For example:
      # - name: Run Tests
      #   run: |
      #     cd backend
      #     source venv/bin/activate
      #     python manage.py test


  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write  # This is required for requesting the JWT
      contents: read   # This is required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_750306962B364CBFAB5903A4AC7CB598 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1535E9900A5147EB9C9515428DC5D08F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CD6D8EA8DF9B4ABD8B25EC1A6796221B }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'saramsa-backend'   
          slot-name: 'Production'        
          package: './backend'
        env:
          API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          ENDPOINT_URL: ${{ secrets.AZURE_OPENAI_ENDPOINT_URL }}
          DEPLOYMENT_NAME: ${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME }}
          API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
          AZURE_DEVOPS_ORGANIZATION: ${{ secrets.AZURE_DEVOPS_ORGANIZATION }}
          AZURE_DEVOPS_PROJECT: ${{ secrets.AZURE_DEVOPS_PROJECT }}
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}